version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "feedly-deduplicator"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-b2xpfsubrrw0"
s3_prefix = "feedly-deduplicator"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
