AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Feedly De-duplicator

  Sample SAM Template for feedly de-duplicator that connects to feedly account and marks all duplicated unread articles as read

Parameters:
  FeedlyTokenParamName:
    Type: String
    Default: '/feedly/token'
    Description: Name of the ssm parameter holding feedly token
  FeedlyUserParamName:
    Type: String
    Default: '/feedly/user'
    Description: Name of the ssm parameter holding feedly user
  FeedlyCheckRuleName:
    Type: String
    Default: 'feedly-check'
    Description: Name of the EventBridge Rule for periodically running deduplicator Lambda
  FeedlyCheckRuleSchedule:
    Type: String
    Default: 'cron(0 4/2 * * ? *)'
    Description: Schedule (e.g. cron schedule) for EventBridge Rule of the deduplicator Lambda
  NotificationSnsTopicName:
    Type: String
    Default: 'feedly-deduplicator-notifications'
    Description: Name of the SNS topic in AWS for notifications about feedly deduplicator failures
  NotificationEmail:
    Type: String
    Description: Email to be subscribed to feedly deduplicator notifications

Resources:
  FeedlyToken:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref FeedlyTokenParamName
      Type: 'String'
      Value: '<feedly token placeholder'
  FeedlyUser:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref FeedlyUserParamName
      Type: 'String'
      Value: '<feedly user placeholder'

  NotificationsSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref NotificationSnsTopicName
      DisplayName: !Ref NotificationSnsTopicName
      Subscription:
        - Protocol: email
          Endpoint: !Ref NotificationEmail

  FeedlyDeduplicator:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: feedly-deduplicator
      CodeUri: dist/
      Handler: LambdaHandler.lambdaHandler
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 60
      Environment:
        Variables:
          NOTIFICATION_TOPIC_ARN: !Ref NotificationsSnsTopic
          LOG_LEVEL: 'info'
          FEEDLY_TOKEN_PARAM_NAME: !Ref FeedlyToken
          FEEDLY_USER_PARAM_NAME: !Ref FeedlyUser
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameters
                - ssm:GetParameter
              Resource:
                - arn:aws:ssm:*:*:parameter/${FeedlyTokenParamName}
                - arn:aws:ssm:*:*:parameter/${FeedlyUserParamName}
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref NotificationsSnsTopic
      Events:
        FeedlyCheckRule:
          Type: Schedule
          Properties:
            Description: 'Periodically check feedly for unread articles'
            Name: !Ref FeedlyCheckRuleName
            Schedule: !Ref FeedlyCheckRuleSchedule
