AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Feedly De-duplicator

  Sample SAM Template for feedly de-duplicator that connects to feedly account and marks all duplicated unread articles as read

Resources:
  FeedlyAuth:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: FeedlyAuth
      Description: Feedly auth data
      SecretString: '{"token": "", "user": ""}'

  FeedlyDeduplicator:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: feedly-deduplicator
      CodeUri: dist/
      Handler: index.lambdaHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 60
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref FeedlyAuth
      Events:
        FeedlyCheckRule:
          Type: Schedule
          Properties:
            Description: 'Periodically check feedly for unread articles'
            Name: 'feedly-check'
            Schedule: 'cron(0 4/5 * * ? *)'
